spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.112.115.39:3306/movie?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: chengfei
    password: cheng2108638
  data:
    elasticsearch:
      repositories:true
      cluster-name: movie-title
      cluster-nodes: 47.112.115.39:39006
