spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.112.115.39:3306/movie?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: chengfei
    password: cheng2108638

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.fei.add.ticket.mapper.SaveDataMapper
